/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.techcable.tinyjson;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        TinyJson classUnderTest = new TinyJson();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
